package mi.wong.podiatrist.model;

public enum ProblemName {
    ACHILLES_TENDINITIS,
    COXA_VALGUS,
    COXA_VARUS,
    EXCESSIVE_SUBTALAR_PRONATION,
    HALLUX_ABDUCTO_VALGUS,
    HYPER_MOBILE_FEET,
    ILLIO_TIBIAL_BAND_FRICTION_SYNDROME,
    LOWER_BACK_PAIN,
    MALALIGNMENT_LOWER_LIMBS,
    METATARSALGIA
}