package mi.wong.podiatrist.model;

public enum SuppliedName {
    FORMTHOTICS_BLUE,
    FORMTHOTICS_3_4_DD_BLUE,
    FORMTHOTICS_DD_BLUE,
    FORMTHOTICS_RED,
    FORMTHOTICS_DD_RED,
    FORMTHOTICS_DD_RED_LP,
    FORMTHOTICS_SHOCK_STOP,
    FORMTHOTICS_BURGUNDY,
    FORMTHOTICS_LV_BLACK,
    FORMTHOTICS_LV_GOLF,
    FORMTHOTICS_BLACK,
    FORMTHOTICS_GOLF,
    FORMTHOTICS_JUNIOR_J1,
    FORMTHOTICS_JUNIOR_J2,
    FORMTHOTICS_JUNIOR_J3,
    FORMTHOTICS_JUNIOR_J4,
    EXPRESS_FL_RED,
    EXPRESS_FL_BLUE,
    EXPRESS_3_4_RED,
    EXPRESS_3_4_BLUE,
    COMFORT_3_4_CHARCOAL,
    RUBBER_3_4_INSOLES,
    SILIPOS_WONDERSPUR,
    SILIPOS_WONDERCUP,
    SILIPOS_WONDERSPORT
}